var nova = "C";
console.log(nova);
nova = "O";
console.log(nova);
nova = "M";
console.log(nova);
nova = " ";
console.log(nova);
nova ="G";
console.log(nova);
nova ='R';
console.log(nova);
nova ='A';
console.log(nova);
nova ='N'; 
console.log(nova);
nova ='D'; 
console.log(nova);
nova ='E';
console.log(nova);
nova ='S';
console.log(nova);
nova = " ";
console.log(nova);
nova ='P'; 
console.log(nova);
nova ='O'; 
console.log(nova);
nova ='D'; 
console.log(nova);
nova ='E'; 
console.log(nova);
nova ='R'; 
console.log(nova);
nova ='S'; 
console.log(nova);
nova =" ";
console.log(nova);
nova ='V'; 
console.log(nova);
nova ='E';
console.log(nova);
nova ='M';
console.log(nova);
nova =" ";
console.log(nova);
nova ='G';
console.log(nova);
nova ='R'; 
console.log(nova);
nova ='A'; 
console.log(nova);
nova ='N';
console.log(nova);
nova ='D'; 
console.log(nova);
nova ='E'; 
console.log(nova);
nova ='S'; 
console.log(nova);
nova =" ";
console.log(nova);
nova ='R'; 
console.log(nova);
nova ='E'; 
console.log(nova);
nova ='S'; 
console.log(nova);
nova ='P'; 
console.log(nova);
nova ='O';
console.log(nova);
nova ='N'; 
console.log(nova);
nova ='S';
console.log(nova);
nova ='A';
console.log(nova);
nova ='B';
console.log(nova);
nova ='I';
console.log(nova);
nova ='L';
console.log(nova);
nova ='I';
console.log(nova);
nova ='D';
console.log(nova);
nova ='A';
console.log(nova);
nova ='D';
console.log(nova);
nova ='E';
console.log(nova);
nova ='S';
console.log(nova);